"""Static catalog for Widad International Volunteers — 8 countries,
24 volunteering projects and 24 local-language courses.

Content is French (site is FR-only per client). Images are pre-verified
real Unsplash photographs mapped to each theme.
"""


def _img(pid, w=1100):
    return f"https://images.unsplash.com/photo-{pid}?auto=format&fit=crop&w={w}&q=80"


# Verified image pool (id -> theme)
IMG = {
    "kids_arts": _img("1503454537195-1dcabb73ffb9"),
    "kids_group": _img("1497486751825-1233686d5d80"),
    "kids_play": _img("1488521787991-ed7bbaae773c"),
    "kids_rural": _img("1594708767771-a7502209ff51"),
    "classroom": _img("1509062522246-3755977927d7"),
    "students_study": _img("1523240795612-9a054b0db644"),
    "language_class": _img("1571260899304-425eee4c7efc"),
    "graduation": _img("1541339907198-e08756dedf3f"),
    "digital_youth": _img("1531482615713-2afd69097998"),
    "meeting": _img("1517048676732-d65bc937f952"),
    "coworking": _img("1521737604893-d14cc237f11d"),
    "women_mentor": _img("1590650516494-0c8e4a4dd67e"),
    "business_plan": _img("1454165804606-c3d57bc86b40"),
    "hands_together": _img("1531206715517-5c0ba140b2b8"),
    "exchange": _img("1604881988758-f76ad2f7aac1"),
    "sport": _img("1544033527-b192daee1f5b"),
    "field_sunset": _img("1500382017468-9049fed747ef"),
    "rice_farmer": _img("1520052203542-d3095f1b6cf0"),
    "compost": _img("1416879595882-3373a0480b5b"),
    "forest": _img("1441974231531-c6227db76b6e"),
    "water_nature": _img("1497436072909-60f360e1d4b1"),
    "market_produce": _img("1464226184884-fa280b87c399"),
    "market_stalls": _img("1533900298318-6b8da08a523e"),
    "food": _img("1595535873420-a599195b3f4a"),
    "solar": _img("1509391366360-2e959784a276"),
    "wind": _img("1466611653911-95081537e5b7"),
    "textile": _img("1556905055-8f358a7a47b2"),
    "pottery1": _img("1565193566173-7a0ee3dbe261"),
    "pottery2": _img("1610701596007-11502861dcfa"),
    "savanna_tree": _img("1547471080-7cc2caa01a7e", 1600),
    "backpacker": _img("1527631746610-bca00a040d60", 1400),
    "safari": _img("1516426122078-c23e76319801"),
    "giraffe": _img("1523805009345-7448845a9e53"),
    "desert_camels": _img("1489493585363-d69421e0edd3"),
    "desert_canyon": _img("1509316785289-025f5b846b35"),
}

HERO_IMAGE = IMG["savanna_tree"]
COURSES_HERO = IMG["language_class"]

COUNTRIES = [
    {"slug": "cameroun", "name": "Cameroun", "flag": "🇨🇲"},
    {"slug": "mali", "name": "Mali", "flag": "🇲🇱"},
    {"slug": "nigeria", "name": "Nigeria", "flag": "🇳🇬"},
    {"slug": "senegal", "name": "Sénégal", "flag": "🇸🇳"},
    {"slug": "maroc", "name": "Maroc", "flag": "🇲🇦"},
    {"slug": "benin", "name": "Bénin", "flag": "🇧🇯"},
    {"slug": "burkina-faso", "name": "Burkina Faso", "flag": "🇧🇫"},
    {"slug": "niger", "name": "Niger", "flag": "🇳🇪"},
]

# Category code -> label
CATEGORIES = {
    "EDU": "Éducation",
    "SOCI": "Social",
    "ENV": "Environnement",
    "SANT": "Santé",
    "ENTR": "Entrepreneuriat",
    "LANG": "Langue",
}


def _p(country, flag, slug, title, city, age_min, age_max, amount, duration, cats, desc, img):
    return {
        "slug": slug,
        "country": country["name"],
        "country_slug": country["slug"],
        "flag": flag,
        "title": title,
        "city": city,
        "age_min": age_min,
        "age_max": age_max,
        "age_label": f"{age_min}-{age_max} ans",
        "amount": float(amount),
        "currency": "eur",
        "duration": duration,
        "categories": cats,
        "description": desc,
        "image": img,
        "type": "project",
    }


C = {c["slug"]: c for c in COUNTRIES}

PROJECTS = [
    # CAMEROUN
    _p(C["cameroun"], "🇨🇲", "rehabilitation-centre-enfants-bafoussam",
       "Réhabilitation et animation d'un centre pour enfants vulnérables", "Bafoussam",
       18, 55, 320, "3 à 8 semaines", ["EDU", "SOCI"],
       "Les volontaires participent à la rénovation légère d'un centre d'accueil (peinture, mobilier, espace de jeux), animent des ateliers scolaires de soutien (lecture, calcul) et des activités artistiques et sportives pour des enfants en situation de vulnérabilité. Encadrement quotidien par l'équipe éducative locale, restitution hebdomadaire des progrès des enfants.",
       IMG["kids_arts"]),
    _p(C["cameroun"], "🇨🇲", "agroforesterie-communautaire-bandjoun",
       "Appui à l'agroforesterie communautaire", "Bandjoun",
       18, 60, 290, "2 à 6 semaines", ["ENV"],
       "Projet agricole participatif visant à reboiser des parcelles communautaires et à introduire des techniques de compostage et de maraîchage durable auprès de coopératives de femmes. Les volontaires travaillent aux côtés des agriculteurs locaux, participent aux plantations et à des sessions de formation technique.",
       IMG["compost"]),
    _p(C["cameroun"], "🇨🇲", "alphabetisation-insertion-jeunes-douala",
       "Alphabétisation et insertion professionnelle des jeunes", "Douala",
       18, 50, 350, "4 à 10 semaines", ["EDU", "ENTR"],
       "Programme d'appui à un centre de formation professionnelle pour jeunes déscolarisés : cours d'alphabétisation, ateliers de couture/menuiserie, et accompagnement à la recherche de stage. Les volontaires co-animent les modules avec les formateurs locaux et contribuent à l'équipement du centre.",
       IMG["digital_youth"]),

    # MALI
    _p(C["mali"], "🇲🇱", "soutien-scolaire-cantine-segou",
       "Soutien scolaire et cantine communautaire", "Ségou",
       18, 55, 300, "3 à 8 semaines", ["EDU", "SANT"],
       "Appui à une école primaire rurale : cours de soutien en français et en calcul, aide à la gestion de la cantine scolaire, sensibilisation à l'hygiène. Hébergement en famille d'accueil pour une immersion complète.",
       IMG["classroom"]),
    _p(C["mali"], "🇲🇱", "maraichage-eau-potable-sikasso",
       "Maraîchage et accès à l'eau potable", "Sikasso",
       18, 60, 310, "4 à 8 semaines", ["ENV", "SANT"],
       "Participation à la construction d'un petit périmètre maraîcher irrigué et à la sensibilisation des familles à la gestion de l'eau. Travail aux côtés d'ingénieurs locaux et de coopératives agricoles féminines.",
       IMG["water_nature"]),
    _p(C["mali"], "🇲🇱", "artisanat-patrimoine-bamako",
       "Artisanat et valorisation du patrimoine culturel", "Bamako",
       18, 50, 340, "2 à 6 semaines", ["SOCI", "ENTR"],
       "Accompagnement d'une coopérative d'artisans (teinture bogolan, bijouterie) pour structurer la vente en ligne et l'accueil de visiteurs. Les volontaires participent aux ateliers de création et à la formation en marketing digital de base.",
       IMG["market_stalls"]),

    # NIGERIA
    _p(C["nigeria"], "🇳🇬", "orphelinat-education-ibadan",
       "Soutien à un orphelinat et activités éducatives", "Ibadan",
       18, 55, 330, "3 à 8 semaines", ["SOCI", "EDU"],
       "Encadrement d'enfants en orphelinat : aide aux devoirs, activités sportives et artistiques, appui logistique (repas, entretien des locaux). Formation continue assurée par l'équipe encadrante locale.",
       IMG["kids_group"]),
    _p(C["nigeria"], "🇳🇬", "entrepreneuriat-jeunes-femmes-lagos",
       "Initiative entrepreneuriale pour jeunes femmes", "Lagos",
       18, 45, 360, "2 à 6 semaines", ["ENTR", "SOCI"],
       "Programme d'incubation courte durée pour jeunes entrepreneuses (couture, restauration, e-commerce) : ateliers de gestion, mentorat individuel, aide à la structuration de micro-business plans.",
       IMG["women_mentor"]),
    _p(C["nigeria"], "🇳🇬", "assainissement-environnement-abuja",
       "Assainissement et sensibilisation environnementale", "Abuja",
       18, 60, 300, "3 à 6 semaines", ["ENV"],
       "Actions de nettoyage communautaire, installation de points de collecte de déchets recyclables et campagnes de sensibilisation dans les écoles sur la gestion des ordures et le recyclage.",
       IMG["hands_together"]),

    # SÉNÉGAL
    _p(C["senegal"], "🇸🇳", "appui-pedagogique-thies",
       "Appui pédagogique en école primaire", "Thiès",
       18, 55, 310, "3 à 8 semaines", ["EDU"],
       "Renfort pédagogique auprès d'enseignants locaux (français, mathématiques), organisation de bibliothèques mobiles et d'ateliers de lecture. Immersion en famille d'accueil sénégalaise.",
       IMG["students_study"]),
    _p(C["senegal"], "🇸🇳", "protection-tortues-ecotourisme-saint-louis",
       "Protection des tortues et écotourisme communautaire", "Saint-Louis",
       18, 55, 320, "2 à 6 semaines", ["ENV"],
       "Participation à la protection d'un site naturel classé, sensibilisation des pêcheurs locaux à la préservation de la faune, et appui au développement de circuits d'écotourisme villageois générateurs de revenus.",
       IMG["safari"]),
    _p(C["senegal"], "🇸🇳", "couture-entrepreneuriat-textile-dakar",
       "Formation à la couture et à l'entrepreneuriat textile", "Dakar",
       18, 50, 340, "3 à 8 semaines", ["ENTR", "SOCI"],
       "Accompagnement d'un atelier de confection textile local : perfectionnement technique, appui à la commercialisation, initiation à la gestion d'un petit atelier de production.",
       IMG["textile"]),

    # MAROC
    _p(C["maroc"], "🇲🇦", "aide-enfants-difficulte-rabat",
       "Soutien et aide aux enfants en difficulté", "Rabat",
       18, 60, 350, "2 à 8 semaines", ["SOCI", "EDU"],
       "Animation d'ateliers éducatifs (danse, arts plastiques, origami, recyclage, jardinage) et d'activités sportives variées (conditionnement physique, golf, équitation, judo, football) pour des enfants suivis par une association marocaine locale.",
       IMG["kids_play"]),
    _p(C["maroc"], "🇲🇦", "renovation-ecole-atlas-marrakech",
       "Rénovation d'école rurale dans l'Atlas", "Marrakech (Atlas)",
       18, 55, 330, "3 à 6 semaines", ["EDU", "ENV"],
       "Travaux légers de rénovation d'écoles de montagne (peinture, mobilier, sanitaires), distribution de fournitures scolaires, animation d'activités périscolaires auprès des enfants berbères de la région.",
       IMG["kids_rural"]),
    _p(C["maroc"], "🇲🇦", "artisanat-cooperatives-femmes-fes",
       "Artisanat traditionnel et coopératives de femmes", "Fès",
       18, 50, 340, "2 à 6 semaines", ["ENTR", "SOCI"],
       "Appui à une coopérative féminine de tissage et de poterie : formation en gestion de petite entreprise, aide à la mise en valeur des produits, participation aux ateliers de production artisanale.",
       IMG["pottery1"]),

    # BÉNIN
    _p(C["benin"], "🇧🇯", "alphabetisation-sante-abomey",
       "Alphabétisation et santé communautaire", "Abomey",
       18, 55, 300, "3 à 8 semaines", ["EDU", "SANT"],
       "Cours d'alphabétisation pour adultes, campagnes de sensibilisation à l'hygiène et à la santé maternelle en partenariat avec un dispensaire local.",
       IMG["classroom"]),
    _p(C["benin"], "🇧🇯", "reboisement-agriculture-durable-porto-novo",
       "Reboisement et agriculture durable", "Porto-Novo",
       18, 60, 290, "2 à 6 semaines", ["ENV"],
       "Plantation d'arbres fruitiers et forestiers, initiation aux techniques agroécologiques auprès de groupements paysans, sensibilisation environnementale dans les écoles avoisinantes.",
       IMG["forest"]),
    _p(C["benin"], "🇧🇯", "centre-accueil-enfants-cotonou",
       "Appui à un centre d'accueil pour enfants", "Cotonou",
       18, 55, 320, "3 à 8 semaines", ["SOCI", "EDU"],
       "Soutien scolaire, activités ludiques et artistiques, aide à la gestion quotidienne d'un centre d'accueil pour enfants en situation difficile.",
       IMG["kids_arts"]),

    # BURKINA FASO
    _p(C["burkina-faso"], "🇧🇫", "appui-scolaire-latrines-koudougou",
       "Appui scolaire et construction de latrines", "Koudougou",
       18, 55, 300, "3 à 8 semaines", ["EDU", "SANT"],
       "Soutien scolaire dans une école primaire rurale et participation à la construction de latrines et de points d'eau pour améliorer les conditions sanitaires de l'établissement.",
       IMG["classroom"]),
    _p(C["burkina-faso"], "🇧🇫", "cooperative-agricole-securite-alimentaire-bobo-dioulasso",
       "Coopérative agricole et sécurité alimentaire", "Bobo-Dioulasso",
       18, 60, 310, "2 à 6 semaines", ["ENV", "ENTR"],
       "Appui à une coopérative de production de céréales (mil, sorgho) : techniques de stockage, transformation agroalimentaire, formation en gestion coopérative.",
       IMG["rice_farmer"]),
    _p(C["burkina-faso"], "🇧🇫", "autonomisation-femmes-artisanat-ouagadougou",
       "Autonomisation des femmes par l'artisanat", "Ouagadougou",
       18, 50, 330, "2 à 6 semaines", ["ENTR", "SOCI"],
       "Accompagnement d'un groupement de femmes tisserandes (faso dan fani) : perfectionnement technique, structuration commerciale, sensibilisation à l'épargne collective.",
       IMG["textile"]),

    # NIGER
    _p(C["niger"], "🇳🇪", "soutien-scolaire-descolarisation-maradi",
       "Soutien scolaire et lutte contre la déscolarisation", "Maradi",
       18, 55, 290, "3 à 8 semaines", ["EDU", "SOCI"],
       "Cours de soutien scolaire, sensibilisation des familles au maintien des filles à l'école, distribution de kits scolaires en partenariat avec des enseignants locaux.",
       IMG["students_study"]),
    _p(C["niger"], "🇳🇪", "eau-maraichage-sahel-zinder",
       "Accès à l'eau et maraîchage en zone sahélienne", "Zinder",
       18, 60, 300, "2 à 6 semaines", ["ENV", "SANT"],
       "Participation à la réhabilitation de puits communautaires et à la mise en place de jardins maraîchers résilients à la sécheresse, en lien avec des coopératives locales.",
       IMG["field_sunset"]),
    _p(C["niger"], "🇳🇪", "formation-professionnelle-jeunes-niamey",
       "Formation professionnelle des jeunes", "Niamey",
       18, 50, 320, "3 à 8 semaines", ["EDU", "ENTR"],
       "Appui à un centre de formation en mécanique, électricité et informatique de base pour jeunes déscolarisés ; accompagnement à l'insertion professionnelle et aux stages en entreprise locale.",
       IMG["digital_youth"]),
]


def _co(country, flag, slug, language, city, age_min, amount, session, teaching, desc, schedule, img):
    return {
        "slug": slug,
        "country": country["name"],
        "country_slug": country["slug"],
        "flag": flag,
        "language": language,
        "title": f"{country['name']} : Cours de {language} à {city}",
        "city": city,
        "age_min": age_min,
        "age_label": f"{age_min} ans et +",
        "amount": float(amount),
        "currency": "eur",
        "session": session,
        "teaching": teaching,
        "description": desc,
        "schedule": schedule,
        "image": img,
        "categories": ["LANG"],
        "type": "course",
    }


COURSES = [
    # CAMEROUN
    _co(C["cameroun"], "🇨🇲", "cameroun-ewondo-yaounde", "Ewondo", "Yaoundé", 16, 220,
        "Session 4 semaines", "Français + Ewondo",
        "Apprentissage de l'ewondo, langue du peuple Beti, à travers l'immersion quotidienne et la vie en famille d'accueil à Yaoundé.",
        ["Semaines 1-2 : alphabet, phonétique, salutations, vie quotidienne (2h/jour, du lundi au vendredi, 9h-11h).",
         "Semaines 3-4 : conversation, expressions culturelles, mise en pratique au marché et en famille d'accueil (2h/jour, 9h-11h).",
         "Examen oral final le vendredi de la 4e semaine."],
        IMG["language_class"]),
    _co(C["cameroun"], "🇨🇲", "cameroun-duala-douala", "Duala", "Douala", 16, 220,
        "Session 4 semaines", "Français + Duala",
        "Découverte du duala, langue côtière du Cameroun, mêlant grammaire, chants traditionnels et sorties culturelles.",
        ["Semaine 1 : bases grammaticales et vocabulaire courant (2h/jour, 14h-16h).",
         "Semaines 2-3 : dialogues pratiques, chants traditionnels, sorties culturelles guidées (2h/jour).",
         "Semaine 4 : immersion complète avec familles duala et restitution finale."],
        IMG["classroom"]),
    _co(C["cameroun"], "🇨🇲", "cameroun-feefee-bafoussam", "Fe'efe'e (Bamiléké)", "Bafoussam", 16, 200,
        "Session 3 semaines", "Français + Fe'efe'e",
        "Cours intensif de fe'efe'e, langue bamiléké de l'Ouest, avec pratique guidée sur les marchés locaux.",
        ["Cours intensif 3h/jour (9h-12h), du lundi au vendredi.",
         "Semaine 1 : phonétique et salutations.",
         "Semaine 2 : vocabulaire de la vie courante et proverbes.",
         "Semaine 3 : conversation et visite de marchés locaux avec pratique guidée."],
        IMG["market_stalls"]),

    # MALI
    _co(C["mali"], "🇲🇱", "mali-bambara-bamako", "Bambara", "Bamako", 16, 210,
        "Session 4 semaines", "Français + Bambara",
        "Le bambara, langue véhiculaire du Mali, enseigné du quotidien jusqu'à la conversation courante au grand marché de Bamako.",
        ["Cours 2h/jour (8h-10h), lundi-vendredi.",
         "Semaines 1-2 : alphabet, chiffres, salutations.",
         "Semaines 3-4 : conversation courante, expressions imagées, sortie pratique au grand marché de Bamako."],
        IMG["language_class"]),
    _co(C["mali"], "🇲🇱", "mali-fulfulde-mopti", "Fulfulde (Peul)", "Mopti", 16, 210,
        "Session 4 semaines", "Français + Fulfulde",
        "Immersion dans le fulfulde peul, du vocabulaire pastoral à la vie villageoise, avec séjour en familles peules.",
        ["2h/jour (16h-18h).",
         "Semaine 1 : phonétique et politesse.",
         "Semaines 2-3 : vocabulaire pastoral et vie villageoise.",
         "Semaine 4 : immersion chez des familles peules, restitution orale."],
        IMG["classroom"]),
    _co(C["mali"], "🇲🇱", "mali-songhai-gao", "Songhaï", "Gao", 18, 230,
        "Session 3 semaines", "Français + Songhaï",
        "Cours de songhaï en petit groupe autour de la culture du fleuve Niger et de la pêche.",
        ["3h/jour (9h-12h) en petit groupe.",
         "Semaine 1 : bases linguistiques.",
         "Semaine 2 : expressions liées au fleuve Niger et à la pêche.",
         "Semaine 3 : conversation avancée et sortie culturelle."],
        IMG["water_nature"]),

    # NIGERIA
    _co(C["nigeria"], "🇳🇬", "nigeria-yoruba-ibadan", "Yoruba", "Ibadan", 16, 240,
        "Session 4 semaines", "Anglais + Yoruba",
        "Apprentissage du yoruba (tons, proverbes) avec sortie au marché traditionnel Bodija d'Ibadan.",
        ["2h/jour (10h-12h).",
         "Semaines 1-2 : alphabet, tons, salutations.",
         "Semaines 3-4 : conversation, proverbes yoruba, sortie au marché traditionnel Bodija."],
        IMG["language_class"]),
    _co(C["nigeria"], "🇳🇬", "nigeria-igbo-enugu", "Igbo", "Enugu", 16, 240,
        "Session 4 semaines", "Anglais + Igbo",
        "Cours d'igbo axé sur les tons et le vocabulaire familial et commercial, ponctué par un festival culturel local.",
        ["2h/jour (14h-16h).",
         "Semaine 1 : phonétique et tons.",
         "Semaines 2-3 : vocabulaire familial et commercial.",
         "Semaine 4 : mise en pratique lors d'un festival culturel local."],
        IMG["students_study"]),
    _co(C["nigeria"], "🇳🇬", "nigeria-haoussa-kano", "Haoussa", "Kano", 18, 230,
        "Session 3 semaines", "Anglais + Haoussa",
        "Le haoussa du commerce et de l'artisanat, avec visite guidée des souks historiques de Kano.",
        ["3h/jour (9h-12h).",
         "Semaine 1 : alphabet et salutations.",
         "Semaine 2 : vocabulaire du commerce et de l'artisanat.",
         "Semaine 3 : conversation et visite guidée des souks de Kano."],
        IMG["market_stalls"]),

    # SÉNÉGAL
    _co(C["senegal"], "🇸🇳", "senegal-wolof-dakar", "Wolof", "Dakar", 16, 220,
        "Session 4 semaines", "Français + Wolof",
        "Le wolof, langue la plus parlée du Sénégal, de l'alphabet à la conversation au marché Sandaga.",
        ["2h/jour (9h-11h).",
         "Semaines 1-2 : alphabet, salutations, chiffres.",
         "Semaines 3-4 : conversation, expressions courantes, sortie pratique au marché Sandaga."],
        IMG["language_class"]),
    _co(C["senegal"], "🇸🇳", "senegal-pulaar-saint-louis", "Pulaar (Peul)", "Saint-Louis", 16, 210,
        "Session 4 semaines", "Français + Pulaar",
        "Immersion en pulaar autour du vocabulaire pastoral et familial, en milieu peul à Saint-Louis.",
        ["2h/jour (15h-17h).",
         "Semaine 1 : bases phonétiques.",
         "Semaines 2-3 : vocabulaire pastoral et familial.",
         "Semaine 4 : immersion en milieu peul, restitution orale finale."],
        IMG["classroom"]),
    _co(C["senegal"], "🇸🇳", "senegal-serere-thies", "Sérère", "Thiès", 18, 210,
        "Session 3 semaines", "Français + Sérère",
        "Cours de sérère explorant le vocabulaire agricole et religieux traditionnel jusqu'à la conversation avancée.",
        ["3h/jour (9h-12h).",
         "Semaine 1 : alphabet et salutations.",
         "Semaine 2 : vocabulaire agricole et religieux traditionnel.",
         "Semaine 3 : conversation avancée."],
        IMG["students_study"]),

    # MAROC
    _co(C["maroc"], "🇲🇦", "maroc-darija-rabat", "Darija (arabe marocain)", "Rabat", 16, 250,
        "Session 4 semaines", "Français + Darija",
        "La darija du quotidien, de la négociation au souk à la conversation dans la médina de Rabat.",
        ["2h/jour (9h-11h).",
         "Semaines 1-2 : alphabet, salutations, expressions du quotidien.",
         "Semaines 3-4 : conversation, négociation au souk, sortie pratique dans la médina."],
        IMG["language_class"]),
    _co(C["maroc"], "🇲🇦", "maroc-tamazight-marrakech", "Tamazight (Amazigh)", "Marrakech", 16, 240,
        "Session 4 semaines", "Français + Tamazight",
        "Le tamazight et l'alphabet Tifinagh, avec immersion dans un village de l'Atlas.",
        ["2h/jour (14h-16h).",
         "Semaine 1 : alphabet Tifinagh et phonétique.",
         "Semaines 2-3 : vocabulaire de la vie berbère (montagne, artisanat).",
         "Semaine 4 : immersion dans un village de l'Atlas."],
        IMG["pottery2"]),
    _co(C["maroc"], "🇲🇦", "maroc-hassaniya-agadir", "Hassaniya", "Agadir", 18, 230,
        "Session 3 semaines", "Français + Hassaniya",
        "Cours de hassaniya autour de la culture nomade saharienne et de la rencontre avec des locuteurs natifs.",
        ["3h/jour (9h-12h).",
         "Semaine 1 : bases linguistiques.",
         "Semaine 2 : expressions sahariennes et culture nomade.",
         "Semaine 3 : conversation et rencontre avec des locuteurs natifs."],
        IMG["desert_camels"]),

    # BÉNIN
    _co(C["benin"], "🇧🇯", "benin-fon-abomey", "Fon", "Abomey", 16, 210,
        "Session 4 semaines", "Français + Fon",
        "Le fon, langue majeure du Bénin, et la découverte des traditions royales d'Abomey.",
        ["2h/jour (9h-11h).",
         "Semaines 1-2 : alphabet, tons, salutations.",
         "Semaines 3-4 : conversation, découverte des traditions royales d'Abomey en pratique linguistique."],
        IMG["language_class"]),
    _co(C["benin"], "🇧🇯", "benin-yoruba-porto-novo", "Yoruba (Bénin)", "Porto-Novo", 16, 210,
        "Session 4 semaines", "Français + Yoruba",
        "Le yoruba du Bénin, de la phonétique aux proverbes, avec mise en pratique au marché de Porto-Novo.",
        ["2h/jour (15h-17h).",
         "Semaine 1 : phonétique.",
         "Semaines 2-3 : vocabulaire courant et proverbes.",
         "Semaine 4 : mise en pratique au marché de Porto-Novo."],
        IMG["market_stalls"]),
    _co(C["benin"], "🇧🇯", "benin-bariba-parakou", "Bariba", "Parakou", 18, 220,
        "Session 3 semaines", "Français + Bariba",
        "Cours de bariba autour du vocabulaire agricole et communautaire, avec locuteurs natifs.",
        ["3h/jour (9h-12h).",
         "Semaine 1 : bases linguistiques.",
         "Semaine 2 : vocabulaire agricole et communautaire.",
         "Semaine 3 : conversation avancée avec locuteurs natifs."],
        IMG["students_study"]),

    # BURKINA FASO
    _co(C["burkina-faso"], "🇧🇫", "burkina-faso-moore-ouagadougou", "Mooré", "Ouagadougou", 16, 210,
        "Session 4 semaines", "Français + Mooré",
        "Le mooré, langue des Mossi, jusqu'à la conversation au grand marché de Ouagadougou.",
        ["2h/jour (9h-11h).",
         "Semaines 1-2 : alphabet, salutations, chiffres.",
         "Semaines 3-4 : conversation, sortie pratique au grand marché de Ouagadougou."],
        IMG["language_class"]),
    _co(C["burkina-faso"], "🇧🇫", "burkina-faso-dioula-bobo-dioulasso", "Dioula", "Bobo-Dioulasso", 16, 210,
        "Session 4 semaines", "Français + Dioula",
        "Le dioula du commerce, avec immersion pratique au marché central de Bobo-Dioulasso.",
        ["2h/jour (14h-16h).",
         "Semaine 1 : phonétique et politesse.",
         "Semaines 2-3 : vocabulaire commercial.",
         "Semaine 4 : immersion pratique au marché central."],
        IMG["market_stalls"]),
    _co(C["burkina-faso"], "🇧🇫", "burkina-faso-fulfulde-dori", "Fulfulde", "Dori", 18, 220,
        "Session 3 semaines", "Français + Fulfulde",
        "Cours de fulfulde autour du vocabulaire pastoral, avec immersion chez des familles peules.",
        ["3h/jour (9h-12h).",
         "Semaine 1 : bases linguistiques.",
         "Semaine 2 : vocabulaire pastoral.",
         "Semaine 3 : conversation et immersion chez des familles peules."],
        IMG["classroom"]),

    # NIGER
    _co(C["niger"], "🇳🇪", "niger-haoussa-zinder", "Haoussa", "Zinder", 16, 210,
        "Session 4 semaines", "Français + Haoussa",
        "Le haoussa du quotidien, avec sortie pratique au marché de Zinder.",
        ["2h/jour (9h-11h).",
         "Semaines 1-2 : alphabet, salutations.",
         "Semaines 3-4 : conversation, sortie pratique au marché de Zinder."],
        IMG["language_class"]),
    _co(C["niger"], "🇳🇪", "niger-zarma-songhai-niamey", "Zarma-Songhaï", "Niamey", 16, 210,
        "Session 4 semaines", "Français + Zarma",
        "Le zarma-songhaï, du vocabulaire familial à l'immersion en famille d'accueil à Niamey.",
        ["2h/jour (15h-17h).",
         "Semaine 1 : phonétique.",
         "Semaines 2-3 : vocabulaire courant et familial.",
         "Semaine 4 : immersion en famille d'accueil à Niamey."],
        IMG["students_study"]),
    _co(C["niger"], "🇳🇪", "niger-tamasheq-agadez", "Tamasheq", "Agadez", 18, 230,
        "Session 3 semaines", "Français + Tamasheq",
        "Le tamasheq touareg et l'alphabet Tifinagh, autour du vocabulaire nomade et désertique.",
        ["3h/jour (9h-12h).",
         "Semaine 1 : bases linguistiques et alphabet Tifinagh.",
         "Semaine 2 : vocabulaire nomade et désertique.",
         "Semaine 3 : conversation avancée avec locuteurs touaregs."],
        IMG["desert_canyon"]),
]
